stages:
  - test

image: gradle:8.10.2-jdk21

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .gradle/
    - build/

test:
  stage: test
  script:
    - cd server
    - chmod +x ./gradlew
    - ./gradlew clean test
