spring.application.name=medivault

spring.datasource.url=jdbc:h2:file:./server/demo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create/drop tables (good for dev)
spring.jpa.hibernate.ddl-auto=update

# Webauthn config
authn.hostname=localhost
authn.display=Medivault
authn.origin=http://localhost:8080

