spring.application.name=medivault

spring.datasource.url=jdbc:h2:file:./server/demo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create/drop tables (good for dev)
spring.jpa.hibernate.ddl-auto=update

# WebAuthn config
authn.hostname=localhost
authn.display=Medivault
authn.origin=https://localhost:8443

# HTTPS
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:medivault.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=medivault

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# hCaptcha config
hcaptcha.secret=${HCAPTCHA_SECRET}
hcaptcha.verify-url=https://hcaptcha.com/siteverify

# Enable debug logging for hCaptcha service to help troubleshooting
logging.level.ssd.medivault.auth=DEBUG
