plugins {
    id 'java'
    id 'application'
}

group = 'ssd'
version = '0.0.1-SNAPSHOT'
description = 'Secure append-only audit log server for Medivault'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'ssd.medivault.logserver.LogServer'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

tasks.named('test') {
    useJUnitPlatform()
}

